/**
 * Scenario Generator - GENERATED FILE
 *
 * This file is automatically generated from definitions/scenarios.json
 * DO NOT EDIT MANUALLY - changes will be overwritten
 *
 * To modify scenarios, edit definitions/scenarios.json and run:
 *     python scripts/generate_typescript.py
 *
 * Generates randomized game scenarios for tournaments
 */

import type { Scenario } from '../types';

/**
 * Scenario type categories
 * Must match bucket_brigade/envs/scenarios.py SCENARIO_REGISTRY
 */
export const SCENARIO_TYPES = {
  DEFAULT: 'default',
  EASY: 'easy',
  HARD: 'hard',
  TRIVIAL_COOPERATION: 'trivial_cooperation',
  EARLY_CONTAINMENT: 'early_containment',
  GREEDY_NEIGHBOR: 'greedy_neighbor',
  SPARSE_HEROICS: 'sparse_heroics',
  REST_TRAP: 'rest_trap',
  CHAIN_REACTION: 'chain_reaction',
  DECEPTIVE_CALM: 'deceptive_calm',
  OVERCROWDING: 'overcrowding',
  MIXED_MOTIVATION: 'mixed_motivation',
} as const;

export type ScenarioType = (typeof SCENARIO_TYPES)[keyof typeof SCENARIO_TYPES];


/**
 * Scenario type definitions with parameter ranges
 * Parameters must match bucket_brigade/envs/scenarios.py exactly
 */
const SCENARIO_TEMPLATES: Record<
  ScenarioType,
  {
    name: string;
    description: string;
    parameters: Partial<Scenario>;
  }
> = {
  [SCENARIO_TYPES.DEFAULT]: {
    name: 'Default',
    description: 'Standard balanced scenario for general testing',
    parameters: {
      beta: 0.25,
      kappa: 0.5,
      A: 100.0,
      L: 100.0,
      c: 0.5,
      rho_ignite: 0.2,
      N_min: 12,
      p_spark: 0.02,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.EASY]: {
    name: 'Easy',
    description: 'Low difficulty with favorable conditions - low fire spread, high extinguish rate',
    parameters: {
      beta: 0.1,
      kappa: 0.8,
      A: 100.0,
      L: 100.0,
      c: 0.5,
      rho_ignite: 0.1,
      N_min: 10,
      p_spark: 0.01,
      N_spark: 10,
    },
  },
  [SCENARIO_TYPES.HARD]: {
    name: 'Hard',
    description: 'High difficulty with challenging conditions - high fire spread, low extinguish rate',
    parameters: {
      beta: 0.4,
      kappa: 0.3,
      A: 100.0,
      L: 100.0,
      c: 0.5,
      rho_ignite: 0.3,
      N_min: 15,
      p_spark: 0.05,
      N_spark: 15,
    },
  },
  [SCENARIO_TYPES.TRIVIAL_COOPERATION]: {
    name: 'Trivial Cooperation',
    description: 'Easy fires reward universal cooperation',
    parameters: {
      beta: 0.15,
      kappa: 0.9,
      A: 100.0,
      L: 100.0,
      c: 0.5,
      rho_ignite: 0.1,
      N_min: 12,
      p_spark: 0.0,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.EARLY_CONTAINMENT]: {
    name: 'Early Containment',
    description: 'Fires start aggressive but can be stopped early',
    parameters: {
      beta: 0.35,
      kappa: 0.6,
      A: 100.0,
      L: 100.0,
      c: 0.5,
      rho_ignite: 0.3,
      N_min: 12,
      p_spark: 0.02,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.GREEDY_NEIGHBOR]: {
    name: 'Greedy Neighbor',
    description: 'Social dilemma between self-interest and cooperation',
    parameters: {
      beta: 0.15,
      kappa: 0.4,
      A: 100.0,
      L: 100.0,
      c: 1.0,
      rho_ignite: 0.2,
      N_min: 12,
      p_spark: 0.02,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.SPARSE_HEROICS]: {
    name: 'Sparse Heroics',
    description: 'Few workers can make the difference',
    parameters: {
      beta: 0.1,
      kappa: 0.5,
      A: 100.0,
      L: 100.0,
      c: 0.8,
      rho_ignite: 0.15,
      N_min: 20,
      p_spark: 0.02,
      N_spark: 20,
    },
  },
  [SCENARIO_TYPES.REST_TRAP]: {
    name: 'Rest Trap',
    description: 'Fires usually extinguish themselves, but not always',
    parameters: {
      beta: 0.05,
      kappa: 0.95,
      A: 100.0,
      L: 100.0,
      c: 0.2,
      rho_ignite: 0.1,
      N_min: 12,
      p_spark: 0.02,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.CHAIN_REACTION]: {
    name: 'Chain Reaction',
    description: 'High spread demands distributed firefighting teams',
    parameters: {
      beta: 0.45,
      kappa: 0.6,
      A: 100.0,
      L: 100.0,
      c: 0.7,
      rho_ignite: 0.3,
      N_min: 15,
      p_spark: 0.03,
      N_spark: 15,
    },
  },
  [SCENARIO_TYPES.DECEPTIVE_CALM]: {
    name: 'Deceptive Calm',
    description: 'Honest signaling rewarded during occasional flare-ups',
    parameters: {
      beta: 0.25,
      kappa: 0.6,
      A: 100.0,
      L: 100.0,
      c: 0.4,
      rho_ignite: 0.1,
      N_min: 20,
      p_spark: 0.05,
      N_spark: 20,
    },
  },
  [SCENARIO_TYPES.OVERCROWDING]: {
    name: 'Overcrowding',
    description: 'Too many workers reduce efficiency',
    parameters: {
      beta: 0.2,
      kappa: 0.3,
      A: 50.0,
      L: 100.0,
      c: 0.6,
      rho_ignite: 0.1,
      N_min: 12,
      p_spark: 0.02,
      N_spark: 12,
    },
  },
  [SCENARIO_TYPES.MIXED_MOTIVATION]: {
    name: 'Mixed Motivation',
    description: 'House ownership creates conflicting incentives',
    parameters: {
      beta: 0.3,
      kappa: 0.5,
      A: 100.0,
      L: 100.0,
      c: 0.6,
      rho_ignite: 0.2,
      N_min: 15,
      p_spark: 0.03,
      N_spark: 15,
    },
  },
};


/**
 * Generate a random scenario of a specific type
 */
export function generateScenario(
  type: ScenarioType,
  numAgents: number,
  _seed?: number,
): Scenario {
  const template = SCENARIO_TEMPLATES[type];

  // Add small random variations to parameters
  const variance = 0.1; // 10% variation
  const randomize = (base: number) => {
    const factor = 1 + (Math.random() - 0.5) * variance;
    return Math.max(0, base * factor);
  };

  return {
    beta: randomize(template.parameters.beta ?? 0.25),
    kappa: randomize(template.parameters.kappa ?? 0.5),
    A: template.parameters.A ?? 100,
    L: template.parameters.L ?? 100,
    c: randomize(template.parameters.c ?? 0.5),
    rho_ignite: randomize(template.parameters.rho_ignite ?? 0.2),
    N_min: template.parameters.N_min ?? 12,
    p_spark: randomize(template.parameters.p_spark ?? 0.02),
    N_spark: template.parameters.N_spark ?? 12,
    num_agents: numAgents,
  };
}

/**
 * Generate random scenario (any type)
 */
export function generateRandomScenario(numAgents: number, seed?: number): Scenario {
  const types = Object.values(SCENARIO_TYPES);
  const randomType = types[Math.floor(Math.random() * types.length)];
  return generateScenario(randomType, numAgents, seed);
}

/**
 * Generate balanced distribution of scenarios
 */
export function generateScenarioSet(
  numScenarios: number,
  numAgents: number,
  seed?: number,
): Array<{ scenario: Scenario; type: ScenarioType }> {
  const scenarios: Array<{ scenario: Scenario; type: ScenarioType }> = [];
  const types = Object.values(SCENARIO_TYPES);

  // Distribute evenly across scenario types
  for (let i = 0; i < numScenarios; i++) {
    const type = types[i % types.length];
    scenarios.push({
      scenario: generateScenario(type, numAgents, seed),
      type,
    });
  }

  // Shuffle for randomness
  for (let i = scenarios.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [scenarios[i], scenarios[j]] = [scenarios[j], scenarios[i]];
  }

  return scenarios;
}

/**
 * Get scenario template info
 */
export function getScenarioTemplate(type: ScenarioType) {
  return SCENARIO_TEMPLATES[type];
}

/**
 * Get all scenario types
 */
export function getAllScenarioTypes(): ScenarioType[] {
  return Object.values(SCENARIO_TYPES);
}
