"""
Random scenario sampler for Bucket Brigade environments.

This module lives separately from `scenarios_generated.py` because that file
is autogenerated from `definitions/scenarios.json` and is overwritten by the
generator. `random_scenario` is a hand-written sampler that produces a fresh
`Scenario` with parameters drawn from reasonable distributions, useful for
fuzz testing and batch experiment runs.

Restored as part of fixing issue #133 (stale import of `random_scenario`
blocked pytest collection of `tests/test_environment.py`). The function was
removed in commit 27c76e74 ("refactor: Remove old scenarios.py in favor of
generated version") but never replaced.
"""

from typing import Optional

import numpy as np

from .scenarios_generated import Scenario


def random_scenario(num_agents: int, seed: Optional[int] = None) -> Scenario:
    """Generate a `Scenario` with parameters sampled from reasonable ranges.

    Distributions match the historical implementation (`beta in [0.15, 0.35]`,
    `kappa in [0.4, 0.6]`, etc.), but field names map to the current Rust-
    aligned `Scenario` schema in `scenarios_generated.py`:

    - beta         -> prob_fire_spreads_to_neighbor
    - kappa        -> prob_solo_agent_extinguishes_fire
    - A            -> team_reward_house_survives / reward_own_house_survives
    - L            -> team_penalty_house_burns
    - c            -> cost_to_work_one_night
    - p_spark      -> prob_house_catches_fire
    - N_min        -> min_nights

    Args:
        num_agents: Number of agents in the game.
        seed: Optional random seed for reproducibility. When provided, sets
            `np.random.seed(seed)` for deterministic sampling.

    Returns:
        A `Scenario` instance compatible with `BucketBrigadeEnv`.
    """
    if seed is not None:
        np.random.seed(seed)

    # Spark probability is either 0 or a small positive value
    p_spark_active = float(np.random.uniform(0.01, 0.05))
    prob_house_catches_fire = float(np.random.choice([0.0, p_spark_active]))

    return Scenario(
        prob_fire_spreads_to_neighbor=float(np.random.uniform(0.15, 0.35)),
        prob_solo_agent_extinguishes_fire=float(np.random.uniform(0.4, 0.6)),
        prob_house_catches_fire=prob_house_catches_fire,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        # Per-house ownership rewards preserve the pre-#170 effective magnitudes
        # of +1.0 on saving an owned house and -2.0 per ruined owned house. See
        # issue #170: previously these fields were unused (shadowed by hardcoded
        # constants in the reward loop). They are now wired into rewards.
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=int(np.random.randint(10, 20)),
        num_agents=num_agents,
    )
