"""
Scenario definitions - GENERATED FILE

This file is automatically generated from definitions/scenarios.json
DO NOT EDIT MANUALLY - changes will be overwritten

To modify scenarios, edit definitions/scenarios.json and run:
    python scripts/generate_python.py

Parameter names match Rust implementation (bucket-brigade-core/src/scenarios.rs)
"""

from dataclasses import dataclass, field
from typing import List, Union
import numpy as np


@dataclass
class Scenario:
    """Represents the stochastic configuration of a game.

    All parameter names match the Rust implementation for consistency.

    The four ownership reward fields (``reward_own_house_survives``,
    ``reward_other_house_survives``, ``penalty_own_house_burns``,
    ``penalty_other_house_burns``) are per-agent vectors of length
    ``num_agents`` (issue #198). Scalar inputs are auto-promoted to
    a length-``num_agents`` list of that value by ``__post_init__``
    for backward compatibility with existing scenario definitions.

    Issue #203 adds three optional spatial-cost fields:
    ``agent_home_positions`` (per-agent home position on the 10-ring,
    empty => fall back to the round-robin ``i % num_agents`` anchor),
    ``distance_cost_alpha`` (additive coefficient, ``0.0`` preserves
    pre-#203 behavior), and ``distance_metric`` (only ``"ring_arc"``
    is supported today).
    """

    # Fire dynamics
    prob_fire_spreads_to_neighbor: float  # Probability fire spreads to adjacent house
    prob_solo_agent_extinguishes_fire: float  # Probability one agent extinguishes fire
    prob_house_catches_fire: float  # Probability house catches fire each night

    # Team scoring (collective outcome)
    team_reward_house_survives: float  # Team reward for each house that survives
    team_penalty_house_burns: float  # Team penalty for each house that burns

    # Individual rewards (ownership-based, per-agent vectors of length num_agents)
    # Scalar inputs are auto-promoted in __post_init__ for backward compat.
    reward_own_house_survives: Union[
        float, List[float]
    ]  # Per-agent reward when own house survives
    reward_other_house_survives: Union[
        float, List[float]
    ]  # Per-agent reward when other house survives
    penalty_own_house_burns: Union[
        float, List[float]
    ]  # Per-agent penalty when own house burns
    penalty_other_house_burns: Union[
        float, List[float]
    ]  # Per-agent penalty when other house burns

    # Costs and structure
    cost_to_work_one_night: float  # Cost incurred when agent chooses to work
    min_nights: int  # Minimum nights before game can end

    # Game setup
    num_agents: int  # Number of agents participating

    # Per-step rest reward (issue #447). Flat reward an agent receives
    # on any step where it RESTs instead of working. Historically a
    # hardcoded ``+0.5`` in the reward implementations; promoted to a
    # scenario weight so every reward term is a scenario parameter and
    # reward-weight scaling is exact. Defaults to ``0.5`` so every
    # pre-#447 scenario is bit-exactly preserved.
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_compute_rewards``
    # and ``bucket-brigade-core/src/engine/rewards.rs`` for the canonical
    # implementation.
    reward_rest: float = 0.5

    # Spatial cost asymmetry (issue #203, optional, additive).
    # Empty ``agent_home_positions`` falls back to the round-robin
    # ``house_owners`` anchor (agent i -> house i). ``distance_cost_alpha
    # == 0.0`` (the implicit default for every pre-#203 scenario)
    # collapses the spatial term to zero, so existing scenarios are
    # bit-exactly unchanged.
    agent_home_positions: List[int] = field(default_factory=list)
    distance_cost_alpha: float = 0.0
    distance_metric: str = "ring_arc"

    # Topology (issue #254). Number of houses on the ring. Defaults to
    # 10 so all 14 pre-#254 scenarios (and any external JSON without the
    # field) remain bit-exact. New scenarios like ``v2_minimal`` set
    # this to a smaller value (2 in the v2 case). The Python env
    # wrappers read ``scenario.num_houses`` to size their action space
    # (``MultiDiscrete([num_houses, 2, 2])``) and observation arrays.
    num_houses: int = 10

    # Action-conditioned reward shaping (issue #259, optional, additive).
    # Both default to ``0.0`` so every pre-#259 scenario is bit-exactly
    # preserved (the env takes a fast-path skip when both knobs are zero).
    # ``action_shaping_alpha`` rewards workers who participated in
    # extinguishing a fire (BURNING -> SAFE this step), credit-shared
    # as ``alpha / workers_at_house``. ``action_shaping_beta`` is a flat
    # per-agent bonus for working at a SAFE house that stays SAFE
    # (preventive presence). REST actions never receive either bonus.
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_compute_rewards``
    # and ``bucket-brigade-core/src/engine/rewards.rs`` for the canonical
    # implementation.
    action_shaping_alpha: float = 0.0
    action_shaping_beta: float = 0.0

    # Dense progress shaping (issue #265, optional, additive). Per-step
    # team-shared reward bonus proportional to the change in the number of
    # SAFE houses between the previous step and the current step:
    #
    #     team_reward += progress_shaping_coef * (cur_safe - prev_safe)
    #
    # Defaults to ``0.0`` so every pre-#265 scenario is bit-exactly
    # preserved (the env takes a fast-path skip when this knob is zero).
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_compute_rewards``
    # and ``bucket-brigade-core/src/engine/rewards.rs`` for the canonical
    # implementation. Sequenced before potential-based shaping (#283) as
    # the cheap mechanical test of the dense-team-signal hypothesis.
    progress_shaping_coef: float = 0.0

    # Potential-based team-welfare shaping (issue #283, Ng-Harada-Russell 1999).
    # Default ``team_welfare_lambda == 0.0`` preserves bit-exact pre-#283
    # behavior (the env takes a fast-path skip when lambda is zero).
    #
    # When non-zero, an aligned per-step bonus ``F(s, a, s') = lambda * (
    # gamma * Phi(s') - Phi(s))`` is added to every agent's reward, shared
    # equally across the team. ``Phi(terminal) = 0`` is enforced exactly so
    # the telescoping sum identity holds:
    #     sum_t gamma^t F_t = lambda * (gamma^T Phi(s_T) - Phi(s_0))
    # which collapses to a constant ``-lambda * Phi(s_0)`` per episode when
    # ``Phi(s_T) == 0`` is enforced. NHR (ICML 1999) guarantees the optimal
    # policy set is preserved under this shaping for any potential ``Phi``.
    #
    # ``team_welfare_kind`` selects the potential function:
    #   - ``"none"``: shaping disabled (also implied when lambda == 0.0)
    #   - ``"team_welfare_closed_form"`` (option B from the issue):
    #         Phi(s) = team_reward * (safe/N) - team_penalty * (ruined/N)
    #                 - 0.5 * team_penalty * (burning/N)
    #     A cheap, debuggable closed-form proxy for team value. Coefficients
    #     are tied to the scenario's team-reward weights so the shaping
    #     signal stays on the same scale as the base reward.
    #
    # ``team_welfare_gamma`` is the NHR discount factor. It is **separate from**
    # the trainer's PPO discount (which is set in JointPPOTrainer) — the
    # theorem holds for *any* gamma applied in ``gamma * Phi(s') - Phi(s)``,
    # but invariance is strongest when this matches the trainer's gamma.
    # Default 1.0 keeps the shaping signal a simple delta when lambda is
    # turned on without a matching trainer discount setting.
    #
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_compute_team_welfare_phi``
    # and ``bucket-brigade-core/src/engine/rewards.rs::team_welfare_phi`` for
    # the canonical implementations (kept in byte-parity).
    team_welfare_lambda: float = 0.0
    team_welfare_gamma: float = 1.0
    team_welfare_kind: str = "none"

    # Position-constrained action validity (issue #251, optional, opt-in).
    # Default ``"always_valid"`` preserves bit-exact pre-#251 behavior:
    # every house index in ``[0, num_houses)`` is a valid target for
    # every agent. Set to ``"adjacent_only"`` to constrain each agent
    # to acting at its home position (``agent_home_positions[i]``) or
    # a directly adjacent house (ring distance exactly 1).
    # Out-of-reach targets are sanitized to home by the env's ``step``
    # before any state mutation (the Python env mirrors the canonical
    # Rust implementation in ``bucket-brigade-core/src/engine/core.rs``).
    # k-hop and continuous-reach variants are deferred to follow-up issues.
    action_validity_mode: str = "always_valid"

    # Continuous extinguish dynamics (issue #253, option D from #234).
    # ``extinguish_mode`` selects the per-step extinguish dynamics:
    #   - ``"bernoulli"`` (default): pre-#253 per-step coin flip with
    #     ``P(extinguish) = 1 - (1-kappa)^k``. Fires that fail their roll
    #     burn out at end-of-step. Bit-exactly preserved for every
    #     pre-#253 scenario.
    #   - ``"continuous"``: damage-accumulation model. Each work step at
    #     a burning house adds ``suppression_per_worker * workers_here``
    #     to a per-house accumulator; fire transitions BURNING -> SAFE
    #     deterministically at threshold 1.0. Fires do NOT auto-burn-out
    #     in this mode (they persist across steps so the accumulator
    #     integrates suppression credit). The smoothing benefit option
    #     D targets comes from credit assignment via the value function.
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_extinguish_fires``
    # and ``bucket-brigade-core/src/engine/phases.rs::extinguish_fires``
    # for the canonical implementations.
    extinguish_mode: str = "bernoulli"
    suppression_per_worker: float = 0.0

    # Within-night commitment mode (issue #252, option C from #234).
    # ``commitment_mode`` selects the per-night turn structure:
    #   - ``"simultaneous"`` (default): pre-#252 single-phase mechanic.
    #     Every agent emits ``[house, mode, signal]`` in a single
    #     round per night. Bit-exact backward compatibility.
    #   - ``"two_phase"``: C1 non-binding signaling. Each night becomes
    #     two micro-rounds at the trainer surface — round-1 emits a
    #     signal only (no movement, no cost, night does not advance),
    #     round-2 observes everyone's round-1 signal (in a new
    #     ``round1_signals`` obs channel) and emits a full
    #     ``[house, mode, signal]`` action. Round-2 mode is
    #     unconstrained by the round-1 signal — policies can emit
    #     ``signal=Work`` round-1 and ``mode=Rest`` round-2 (the
    #     deception channel survives).
    # The two-phase mechanic requires using
    # ``BucketBrigadeEnv.step_two_phase(round1_signals, round2_actions)``
    # instead of ``step``; calling ``step`` on a two-phase scenario
    # raises a clear error.
    commitment_mode: str = "simultaneous"

    def __post_init__(self) -> None:
        """Auto-promote scalar ownership reward fields to per-agent vectors.

        This is the canonical place where scalar -> list promotion happens
        for issue #198. Existing scenarios with scalar JSON values are
        still valid: a scalar ``v`` becomes ``[v] * num_agents``. Lists
        are validated to have exactly ``num_agents`` entries.

        Also validates the #203 spatial fields when present.
        """
        for fname in (
            "reward_own_house_survives",
            "reward_other_house_survives",
            "penalty_own_house_burns",
            "penalty_other_house_burns",
        ):
            value = getattr(self, fname)
            if isinstance(value, (int, float)):
                setattr(self, fname, [float(value)] * self.num_agents)
            else:
                # Already a sequence; coerce to list[float] and validate length.
                promoted = [float(x) for x in value]
                if len(promoted) != self.num_agents:
                    raise ValueError(
                        f"Scenario.{fname} has length {len(promoted)} "
                        f"but num_agents={self.num_agents}. Per-agent "
                        f"ownership reward vectors must match num_agents."
                    )
                setattr(self, fname, promoted)

        # Issue #254 num_houses validation. Must be at least 2 for the
        # spread phase ring math to have distinct neighbors. Kept tight
        # to surface configuration mistakes early rather than blowing
        # up deep in a rollout.
        if self.num_houses < 2:
            raise ValueError(
                f"Scenario.num_houses={self.num_houses} is too small; "
                "must be at least 2."
            )

        # Issue #203 spatial-field validation.
        if self.agent_home_positions:
            positions = [int(p) for p in self.agent_home_positions]
            if len(positions) != self.num_agents:
                raise ValueError(
                    f"Scenario.agent_home_positions has length "
                    f"{len(positions)} but num_agents={self.num_agents}. "
                    "Per-agent home position vectors must match num_agents."
                )
            for i, p in enumerate(positions):
                # Issue #254: range bound is now `num_houses`, not the
                # hardcoded 10. Pre-#254 scenarios are unchanged because
                # `num_houses` defaults to 10.
                if not (0 <= p < self.num_houses):
                    raise ValueError(
                        f"Scenario.agent_home_positions[{i}]={p} "
                        f"is out of range [0, {self.num_houses})."
                    )
            self.agent_home_positions = positions
        # Keep in sync with the Rust allowlist in
        # `bucket-brigade-core/src/scenarios.rs::ALLOWED_DISTANCE_METRICS`.
        # Both sides reject unknown values to prevent silent ring-arc
        # fallback (issue #222 — `engine/rewards.rs` does not branch on
        # this field, so any unrecognized string would otherwise run
        # ring-arc geometry).
        if self.distance_metric != "ring_arc":
            raise ValueError(
                f"Scenario.distance_metric={self.distance_metric!r} "
                "is not supported; only 'ring_arc' is implemented today."
            )

        # Issue #283: potential-based team-welfare shaping allowlist.
        # Keep in sync with the Rust validator in
        # ``bucket-brigade-core/src/scenarios.rs::ALLOWED_TEAM_WELFARE_KINDS``.
        # ``"none"`` is the default and means shaping is disabled even if
        # lambda is non-zero (the env shortcuts on kind="none").
        allowed_team_welfare_kinds = ("none", "team_welfare_closed_form")
        if self.team_welfare_kind not in allowed_team_welfare_kinds:
            raise ValueError(
                f"Scenario.team_welfare_kind={self.team_welfare_kind!r} "
                f"is not supported; allowed values: {allowed_team_welfare_kinds!r}."
            )

        # Issue #251: action_validity_mode allowlist. Keep in sync with
        # the Rust allowlist in
        # ``bucket-brigade-core/src/scenarios.rs::ALLOWED_ACTION_VALIDITY_MODES``.
        # ``"always_valid"`` (default) preserves bit-exact pre-#251 behavior;
        # ``"adjacent_only"`` enables the v1 position-constrained mask.
        allowed_action_validity_modes = ("always_valid", "adjacent_only")
        if self.action_validity_mode not in allowed_action_validity_modes:
            raise ValueError(
                f"Scenario.action_validity_mode={self.action_validity_mode!r} "
                f"is not supported; allowed values: {allowed_action_validity_modes!r}."
            )

        # Issue #253: extinguish_mode allowlist. Keep in sync with the
        # Rust validator in
        # ``bucket-brigade-core/src/scenarios.rs::ALLOWED_EXTINGUISH_MODES``.
        # ``"bernoulli"`` is the default and preserves pre-#253
        # behavior bit-exactly.
        allowed_extinguish_modes = ("bernoulli", "continuous")
        if self.extinguish_mode not in allowed_extinguish_modes:
            raise ValueError(
                f"Scenario.extinguish_mode={self.extinguish_mode!r} "
                f"is not supported; allowed values: {allowed_extinguish_modes!r}."
            )

        # Issue #252: commitment_mode allowlist. Keep in sync with the
        # Rust validator in
        # ``bucket-brigade-core/src/scenarios.rs::ALLOWED_COMMITMENT_MODES``.
        # ``"simultaneous"`` is the default and preserves pre-#252
        # single-phase behavior bit-exactly. ``"two_phase"`` invokes
        # the C1 non-binding signaling mechanic; callers must use
        # ``BucketBrigadeEnv.step_two_phase`` instead of ``step``.
        allowed_commitment_modes = ("simultaneous", "two_phase")
        if self.commitment_mode not in allowed_commitment_modes:
            raise ValueError(
                f"Scenario.commitment_mode={self.commitment_mode!r} "
                f"is not supported; allowed values: {allowed_commitment_modes!r}."
            )

    def to_feature_vector(self) -> np.ndarray:
        """
        Convert scenario parameters to a feature vector for agent conditioning.

        Returns a numpy array with scenario features. The four per-agent
        ownership reward fields are reduced to their mean across agents
        so the feature vector retains its 12-element layout (#198). For
        scenarios with uniform per-agent weights (the legacy scalar-promoted
        case) the mean equals the original scalar value, preserving
        backward compatibility.
        """
        return np.array(
            [
                self.prob_fire_spreads_to_neighbor,
                self.prob_solo_agent_extinguishes_fire,
                self.prob_house_catches_fire,
                self.team_reward_house_survives,
                self.team_penalty_house_burns,
                float(np.mean(self.reward_own_house_survives)),
                float(np.mean(self.reward_other_house_survives)),
                float(np.mean(self.penalty_own_house_burns)),
                float(np.mean(self.penalty_other_house_burns)),
                self.cost_to_work_one_night,
                self.min_nights,
                self.num_agents,
            ],
            dtype=np.float32,
        )


def default_scenario(num_agents: int) -> Scenario:
    """Standard balanced scenario for general testing (ownership rebalanced #197: 1.0/2.0 -> 20.0/40.0 to give PPO a per-agent gradient signal)"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=20.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=40.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def easy_scenario(num_agents: int) -> Scenario:
    """Low difficulty with favorable conditions - low fire spread, high extinguish rate"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.1,
        prob_solo_agent_extinguishes_fire=0.8,
        prob_house_catches_fire=0.01,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=10,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def hard_scenario(num_agents: int) -> Scenario:
    """High difficulty with challenging conditions - high fire spread, low extinguish rate"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.4,
        prob_solo_agent_extinguishes_fire=0.3,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=15,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def trivial_cooperation_scenario(num_agents: int) -> Scenario:
    """Easy fires reward universal cooperation"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.15,
        prob_solo_agent_extinguishes_fire=0.9,
        prob_house_catches_fire=0.0,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def early_containment_scenario(num_agents: int) -> Scenario:
    """Fires start aggressive but can be stopped early"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.35,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def greedy_neighbor_scenario(num_agents: int) -> Scenario:
    """Social dilemma between self-interest and cooperation"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.15,
        prob_solo_agent_extinguishes_fire=0.4,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=1.0,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def sparse_heroics_scenario(num_agents: int) -> Scenario:
    """Few workers can make the difference"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.1,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.8,
        min_nights=20,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def rest_trap_scenario(num_agents: int) -> Scenario:
    """Fires usually extinguish themselves, but not always"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.05,
        prob_solo_agent_extinguishes_fire=0.95,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.2,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def chain_reaction_scenario(num_agents: int) -> Scenario:
    """High spread demands distributed firefighting teams"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.45,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.03,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.7,
        min_nights=15,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def deceptive_calm_scenario(num_agents: int) -> Scenario:
    """Honest signaling rewarded during occasional flare-ups"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.4,
        min_nights=20,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def overcrowding_scenario(num_agents: int) -> Scenario:
    """Too many workers reduce efficiency"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.2,
        prob_solo_agent_extinguishes_fire=0.3,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=50.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.6,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def mixed_motivation_scenario(num_agents: int) -> Scenario:
    """House ownership creates conflicting incentives"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.3,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.03,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.6,
        min_nights=15,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def minimal_specialization_scenario(num_agents: int) -> Scenario:
    """Sanity-check scenario for issue #199: per-agent ownership signal is dominant (50/100 own vs 0 other) and team signal is reduced (10 vs default 100). Disambiguates whether PPO can learn specialization when per-agent gradient signal is truly dominant; if PPO learns this but not default, env design is the issue; if it fails this too, algorithm change (MAPPO/COMA) is needed."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def positional_default_scenario(num_agents: int) -> Scenario:
    """Issue #203 option A: spatial cost asymmetry on the 10-ring. Same reward magnitudes as `default`, but per-agent work cost is base_cost + alpha * ring_dist(home, target). With home positions [0,3,5,8] and alpha=0.1 the cheapest action for each agent is to defend its own neighborhood, creating a per-agent gradient that doesn't rely on reward magnitude differences. When distance_cost_alpha=0 (the implicit default for every other scenario) behavior is bit-exactly identical to today's env."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=20.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=40.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
        agent_home_positions=[0, 3, 5, 8],
        distance_cost_alpha=0.1,
        distance_metric="ring_arc",
    )


def v2_minimal_scenario(num_agents: int) -> Scenario:
    """Issue #254 / option E of architect proposal #234: 2-house x 4-agent PPO learnability diagnostic. Joint action space shrinks to 4 * (2 * 2 * 2) = 32 per-agent moves vs default 4 * (10 * 2 * 2) = 1600, so PPO has a tractable exploration problem. Reward shape mirrors minimal_specialization (per-agent ownership dominates 10 team reward). Ignition rate bumped 0.02->0.05 because at 0.02 a 2-house ring has too many fire-free episodes. Python/Rust only - WASM frontend (web/) is fixed at 10 houses; non-10 scenarios panic in wasm.rs."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=8,
        num_agents=num_agents,
        reward_rest=0.5,
        num_houses=2,
    )


def default_continuous_scenario(num_agents: int) -> Scenario:
    """Issue #253 / option D of architect proposal #234: continuous extinguish dynamics. Mirrors `default` (kappa=0.5) but switches to the damage-accumulation model — each work step at a burning house adds suppression_per_worker * workers_here to a per-house accumulator; the fire transitions BURNING -> SAFE deterministically at threshold 1.0. With suppression_per_worker=kappa=0.5, the one-worker expected nights-to-extinguish matches the Bernoulli baseline (1/kappa=2). The smoothing benefit option D targets comes from credit assignment via the value function: workers who contributed but didn't trigger the threshold this step affected the next-step suppression state, so the critic learns their work matters."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=20.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=40.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
        extinguish_mode="continuous",
        suppression_per_worker=0.5,
    )


def asym_b05_k09_c05_scenario(num_agents: int) -> Scenario:
    """Issue #435: NE phase-diagram cell (beta=0.50, kappa=0.90, c=0.50) promoted to a named scenario. Parameter-identical to make_phase_diagram_scenario(0.5, 0.9, 0.5) on the minimal_specialization base (only beta/kappa/c differ from that base; bit-parity is enforced by tests/test_env_registry.py). The #358 heterogeneous double-oracle search classified this cell `asymmetric_only` (NE team payoff 72.0095 PER EPISODE, 14/20 restarts converged, profile 1xhero + 3xfirefighter; artifacts: experiments/nash/phase_diagram/results.json and bucket_brigade/baselines/release/local/nash/phase_diagram/b0.50_k0.90_c0.50.json) — the regime where the NE itself demands role asymmetry, targeted by het_ppo Phase 2 (#429)."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.5,
        prob_solo_agent_extinguishes_fire=0.9,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


def asym_b09_k09_c05_scenario(num_agents: int) -> Scenario:
    """Issue #435: NE phase-diagram cell (beta=0.90, kappa=0.90, c=0.50) promoted to a named scenario. Parameter-identical to make_phase_diagram_scenario(0.9, 0.9, 0.5) on the minimal_specialization base (only beta/kappa/c differ from that base; bit-parity is enforced by tests/test_env_registry.py). The #358 heterogeneous double-oracle search classified this cell `asymmetric_only` (NE team payoff 72.0095 PER EPISODE, 14/20 restarts converged, profile 1xhero + 3xfirefighter; artifacts: experiments/nash/phase_diagram/results.json and bucket_brigade/baselines/release/local/nash/phase_diagram/b0.90_k0.90_c0.50.json) — the regime where the NE itself demands role asymmetry, targeted by het_ppo Phase 2 (#429)."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.9,
        prob_solo_agent_extinguishes_fire=0.9,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        reward_rest=0.5,
    )


# Registry of all scenarios
SCENARIO_REGISTRY = {
    "default": default_scenario,
    "easy": easy_scenario,
    "hard": hard_scenario,
    "trivial_cooperation": trivial_cooperation_scenario,
    "early_containment": early_containment_scenario,
    "greedy_neighbor": greedy_neighbor_scenario,
    "sparse_heroics": sparse_heroics_scenario,
    "rest_trap": rest_trap_scenario,
    "chain_reaction": chain_reaction_scenario,
    "deceptive_calm": deceptive_calm_scenario,
    "overcrowding": overcrowding_scenario,
    "mixed_motivation": mixed_motivation_scenario,
    "minimal_specialization": minimal_specialization_scenario,
    "positional_default": positional_default_scenario,
    "v2_minimal": v2_minimal_scenario,
    "default_continuous": default_continuous_scenario,
    "asym_b05_k09_c05": asym_b05_k09_c05_scenario,
    "asym_b09_k09_c05": asym_b09_k09_c05_scenario,
}


def get_scenario_by_name(name: str, num_agents: int) -> Scenario:
    """
    Get a scenario by name.

    Args:
        name: Scenario name (e.g., "trivial_cooperation", "default")
        num_agents: Number of agents in the scenario

    Returns:
        Scenario object

    Raises:
        ValueError: If scenario name is invalid

    Example:
        >>> scenario = get_scenario_by_name("trivial_cooperation", num_agents=4)
    """
    if name not in SCENARIO_REGISTRY:
        valid_names = ", ".join(sorted(SCENARIO_REGISTRY.keys()))
        raise ValueError(f"Unknown scenario '{name}'. Valid options: {valid_names}")

    return SCENARIO_REGISTRY[name](num_agents)


def list_scenarios() -> list:
    """
    Get list of available scenario names.

    Returns:
        Sorted list of scenario names

    Example:
        >>> scenarios = list_scenarios()
        >>> print(scenarios)
        ['chain_reaction', 'deceptive_calm', 'default', ...]
    """
    return sorted(SCENARIO_REGISTRY.keys())
