"""
Scenario definitions - GENERATED FILE

This file is automatically generated from definitions/scenarios.json
DO NOT EDIT MANUALLY - changes will be overwritten

To modify scenarios, edit definitions/scenarios.json and run:
    python scripts/generate_python.py

Parameter names match Rust implementation (bucket-brigade-core/src/scenarios.rs)
"""

from dataclasses import dataclass, field
from typing import List, Union
import numpy as np


@dataclass
class Scenario:
    """Represents the stochastic configuration of a game.

    All parameter names match the Rust implementation for consistency.

    The four ownership reward fields (``reward_own_house_survives``,
    ``reward_other_house_survives``, ``penalty_own_house_burns``,
    ``penalty_other_house_burns``) are per-agent vectors of length
    ``num_agents`` (issue #198). Scalar inputs are auto-promoted to
    a length-``num_agents`` list of that value by ``__post_init__``
    for backward compatibility with existing scenario definitions.

    Issue #203 adds three optional spatial-cost fields:
    ``agent_home_positions`` (per-agent home position on the 10-ring,
    empty => fall back to the round-robin ``i % num_agents`` anchor),
    ``distance_cost_alpha`` (additive coefficient, ``0.0`` preserves
    pre-#203 behavior), and ``distance_metric`` (only ``"ring_arc"``
    is supported today).
    """

    # Fire dynamics
    prob_fire_spreads_to_neighbor: float  # Probability fire spreads to adjacent house
    prob_solo_agent_extinguishes_fire: float  # Probability one agent extinguishes fire
    prob_house_catches_fire: float  # Probability house catches fire each night

    # Team scoring (collective outcome)
    team_reward_house_survives: float  # Team reward for each house that survives
    team_penalty_house_burns: float  # Team penalty for each house that burns

    # Individual rewards (ownership-based, per-agent vectors of length num_agents)
    # Scalar inputs are auto-promoted in __post_init__ for backward compat.
    reward_own_house_survives: Union[
        float, List[float]
    ]  # Per-agent reward when own house survives
    reward_other_house_survives: Union[
        float, List[float]
    ]  # Per-agent reward when other house survives
    penalty_own_house_burns: Union[
        float, List[float]
    ]  # Per-agent penalty when own house burns
    penalty_other_house_burns: Union[
        float, List[float]
    ]  # Per-agent penalty when other house burns

    # Costs and structure
    cost_to_work_one_night: float  # Cost incurred when agent chooses to work
    min_nights: int  # Minimum nights before game can end

    # Game setup
    num_agents: int  # Number of agents participating

    # Spatial cost asymmetry (issue #203, optional, additive).
    # Empty ``agent_home_positions`` falls back to the round-robin
    # ``house_owners`` anchor (agent i -> house i). ``distance_cost_alpha
    # == 0.0`` (the implicit default for every pre-#203 scenario)
    # collapses the spatial term to zero, so existing scenarios are
    # bit-exactly unchanged.
    agent_home_positions: List[int] = field(default_factory=list)
    distance_cost_alpha: float = 0.0
    distance_metric: str = "ring_arc"

    # Topology (issue #254). Number of houses on the ring. Defaults to
    # 10 so all 14 pre-#254 scenarios (and any external JSON without the
    # field) remain bit-exact. New scenarios like ``v2_minimal`` set
    # this to a smaller value (2 in the v2 case). The Python env
    # wrappers read ``scenario.num_houses`` to size their action space
    # (``MultiDiscrete([num_houses, 2, 2])``) and observation arrays.
    num_houses: int = 10

    # Action-conditioned reward shaping (issue #259, optional, additive).
    # Both default to ``0.0`` so every pre-#259 scenario is bit-exactly
    # preserved (the env takes a fast-path skip when both knobs are zero).
    # ``action_shaping_alpha`` rewards workers who participated in
    # extinguishing a fire (BURNING -> SAFE this step), credit-shared
    # as ``alpha / workers_at_house``. ``action_shaping_beta`` is a flat
    # per-agent bonus for working at a SAFE house that stays SAFE
    # (preventive presence). REST actions never receive either bonus.
    # See ``bucket_brigade/envs/bucket_brigade_env.py::_compute_rewards``
    # and ``bucket-brigade-core/src/engine/rewards.rs`` for the canonical
    # implementation.
    action_shaping_alpha: float = 0.0
    action_shaping_beta: float = 0.0

    def __post_init__(self) -> None:
        """Auto-promote scalar ownership reward fields to per-agent vectors.

        This is the canonical place where scalar -> list promotion happens
        for issue #198. Existing scenarios with scalar JSON values are
        still valid: a scalar ``v`` becomes ``[v] * num_agents``. Lists
        are validated to have exactly ``num_agents`` entries.

        Also validates the #203 spatial fields when present.
        """
        for fname in (
            "reward_own_house_survives",
            "reward_other_house_survives",
            "penalty_own_house_burns",
            "penalty_other_house_burns",
        ):
            value = getattr(self, fname)
            if isinstance(value, (int, float)):
                setattr(self, fname, [float(value)] * self.num_agents)
            else:
                # Already a sequence; coerce to list[float] and validate length.
                promoted = [float(x) for x in value]
                if len(promoted) != self.num_agents:
                    raise ValueError(
                        f"Scenario.{fname} has length {len(promoted)} "
                        f"but num_agents={self.num_agents}. Per-agent "
                        f"ownership reward vectors must match num_agents."
                    )
                setattr(self, fname, promoted)

        # Issue #254 num_houses validation. Must be at least 2 for the
        # spread phase ring math to have distinct neighbors. Kept tight
        # to surface configuration mistakes early rather than blowing
        # up deep in a rollout.
        if self.num_houses < 2:
            raise ValueError(
                f"Scenario.num_houses={self.num_houses} is too small; "
                "must be at least 2."
            )

        # Issue #203 spatial-field validation.
        if self.agent_home_positions:
            positions = [int(p) for p in self.agent_home_positions]
            if len(positions) != self.num_agents:
                raise ValueError(
                    f"Scenario.agent_home_positions has length "
                    f"{len(positions)} but num_agents={self.num_agents}. "
                    "Per-agent home position vectors must match num_agents."
                )
            for i, p in enumerate(positions):
                # Issue #254: range bound is now `num_houses`, not the
                # hardcoded 10. Pre-#254 scenarios are unchanged because
                # `num_houses` defaults to 10.
                if not (0 <= p < self.num_houses):
                    raise ValueError(
                        f"Scenario.agent_home_positions[{i}]={p} "
                        f"is out of range [0, {self.num_houses})."
                    )
            self.agent_home_positions = positions
        # Keep in sync with the Rust allowlist in
        # `bucket-brigade-core/src/scenarios.rs::ALLOWED_DISTANCE_METRICS`.
        # Both sides reject unknown values to prevent silent ring-arc
        # fallback (issue #222 — `engine/rewards.rs` does not branch on
        # this field, so any unrecognized string would otherwise run
        # ring-arc geometry).
        if self.distance_metric != "ring_arc":
            raise ValueError(
                f"Scenario.distance_metric={self.distance_metric!r} "
                "is not supported; only 'ring_arc' is implemented today."
            )

    def to_feature_vector(self) -> np.ndarray:
        """
        Convert scenario parameters to a feature vector for agent conditioning.

        Returns a numpy array with scenario features. The four per-agent
        ownership reward fields are reduced to their mean across agents
        so the feature vector retains its 12-element layout (#198). For
        scenarios with uniform per-agent weights (the legacy scalar-promoted
        case) the mean equals the original scalar value, preserving
        backward compatibility.
        """
        return np.array(
            [
                self.prob_fire_spreads_to_neighbor,
                self.prob_solo_agent_extinguishes_fire,
                self.prob_house_catches_fire,
                self.team_reward_house_survives,
                self.team_penalty_house_burns,
                float(np.mean(self.reward_own_house_survives)),
                float(np.mean(self.reward_other_house_survives)),
                float(np.mean(self.penalty_own_house_burns)),
                float(np.mean(self.penalty_other_house_burns)),
                self.cost_to_work_one_night,
                self.min_nights,
                self.num_agents,
            ],
            dtype=np.float32,
        )


def default_scenario(num_agents: int) -> Scenario:
    """Standard balanced scenario for general testing (ownership rebalanced #197: 1.0/2.0 -> 20.0/40.0 to give PPO a per-agent gradient signal)"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=20.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=40.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
    )


def easy_scenario(num_agents: int) -> Scenario:
    """Low difficulty with favorable conditions - low fire spread, high extinguish rate"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.1,
        prob_solo_agent_extinguishes_fire=0.8,
        prob_house_catches_fire=0.01,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=10,
        num_agents=num_agents,
    )


def hard_scenario(num_agents: int) -> Scenario:
    """High difficulty with challenging conditions - high fire spread, low extinguish rate"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.4,
        prob_solo_agent_extinguishes_fire=0.3,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=15,
        num_agents=num_agents,
    )


def trivial_cooperation_scenario(num_agents: int) -> Scenario:
    """Easy fires reward universal cooperation"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.15,
        prob_solo_agent_extinguishes_fire=0.9,
        prob_house_catches_fire=0.0,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
    )


def early_containment_scenario(num_agents: int) -> Scenario:
    """Fires start aggressive but can be stopped early"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.35,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
    )


def greedy_neighbor_scenario(num_agents: int) -> Scenario:
    """Social dilemma between self-interest and cooperation"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.15,
        prob_solo_agent_extinguishes_fire=0.4,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=1.0,
        min_nights=12,
        num_agents=num_agents,
    )


def sparse_heroics_scenario(num_agents: int) -> Scenario:
    """Few workers can make the difference"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.1,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.8,
        min_nights=20,
        num_agents=num_agents,
    )


def rest_trap_scenario(num_agents: int) -> Scenario:
    """Fires usually extinguish themselves, but not always"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.05,
        prob_solo_agent_extinguishes_fire=0.95,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.2,
        min_nights=12,
        num_agents=num_agents,
    )


def chain_reaction_scenario(num_agents: int) -> Scenario:
    """High spread demands distributed firefighting teams"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.45,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.03,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.7,
        min_nights=15,
        num_agents=num_agents,
    )


def deceptive_calm_scenario(num_agents: int) -> Scenario:
    """Honest signaling rewarded during occasional flare-ups"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.6,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.4,
        min_nights=20,
        num_agents=num_agents,
    )


def overcrowding_scenario(num_agents: int) -> Scenario:
    """Too many workers reduce efficiency"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.2,
        prob_solo_agent_extinguishes_fire=0.3,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=50.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.6,
        min_nights=12,
        num_agents=num_agents,
    )


def mixed_motivation_scenario(num_agents: int) -> Scenario:
    """House ownership creates conflicting incentives"""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.3,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.03,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=1.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=2.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.6,
        min_nights=15,
        num_agents=num_agents,
    )


def minimal_specialization_scenario(num_agents: int) -> Scenario:
    """Sanity-check scenario for issue #199: per-agent ownership signal is dominant (50/100 own vs 0 other) and team signal is reduced (10 vs default 100). Disambiguates whether PPO can learn specialization when per-agent gradient signal is truly dominant; if PPO learns this but not default, env design is the issue; if it fails this too, algorithm change (MAPPO/COMA) is needed."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
    )


def positional_default_scenario(num_agents: int) -> Scenario:
    """Issue #203 option A: spatial cost asymmetry on the 10-ring. Same reward magnitudes as `default`, but per-agent work cost is base_cost + alpha * ring_dist(home, target). With home positions [0,3,5,8] and alpha=0.1 the cheapest action for each agent is to defend its own neighborhood, creating a per-agent gradient that doesn't rely on reward magnitude differences. When distance_cost_alpha=0 (the implicit default for every other scenario) behavior is bit-exactly identical to today's env."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.02,
        team_reward_house_survives=100.0,
        team_penalty_house_burns=100.0,
        reward_own_house_survives=20.0,
        reward_other_house_survives=0.0,
        penalty_own_house_burns=40.0,
        penalty_other_house_burns=0.0,
        cost_to_work_one_night=0.5,
        min_nights=12,
        num_agents=num_agents,
        agent_home_positions=[0, 3, 5, 8],
        distance_cost_alpha=0.1,
        distance_metric="ring_arc",
    )


def v2_minimal_scenario(num_agents: int) -> Scenario:
    """Issue #254 / option E of architect proposal #234: 2-house x 4-agent PPO learnability diagnostic. Joint action space shrinks to 4 * (2 * 2 * 2) = 32 per-agent moves vs default 4 * (10 * 2 * 2) = 1600, so PPO has a tractable exploration problem. Reward shape mirrors minimal_specialization (per-agent ownership dominates 10 team reward). Ignition rate bumped 0.02->0.05 because at 0.02 a 2-house ring has too many fire-free episodes. Python/Rust only - WASM frontend (web/) is fixed at 10 houses; non-10 scenarios panic in wasm.rs."""
    return Scenario(
        prob_fire_spreads_to_neighbor=0.25,
        prob_solo_agent_extinguishes_fire=0.5,
        prob_house_catches_fire=0.05,
        team_reward_house_survives=10.0,
        team_penalty_house_burns=10.0,
        reward_own_house_survives=[50.0, 50.0, 50.0, 50.0],
        reward_other_house_survives=[0.0, 0.0, 0.0, 0.0],
        penalty_own_house_burns=[100.0, 100.0, 100.0, 100.0],
        penalty_other_house_burns=[0.0, 0.0, 0.0, 0.0],
        cost_to_work_one_night=0.5,
        min_nights=8,
        num_agents=num_agents,
        num_houses=2,
    )


# Registry of all scenarios
SCENARIO_REGISTRY = {
    "default": default_scenario,
    "easy": easy_scenario,
    "hard": hard_scenario,
    "trivial_cooperation": trivial_cooperation_scenario,
    "early_containment": early_containment_scenario,
    "greedy_neighbor": greedy_neighbor_scenario,
    "sparse_heroics": sparse_heroics_scenario,
    "rest_trap": rest_trap_scenario,
    "chain_reaction": chain_reaction_scenario,
    "deceptive_calm": deceptive_calm_scenario,
    "overcrowding": overcrowding_scenario,
    "mixed_motivation": mixed_motivation_scenario,
    "minimal_specialization": minimal_specialization_scenario,
    "positional_default": positional_default_scenario,
    "v2_minimal": v2_minimal_scenario,
}


def get_scenario_by_name(name: str, num_agents: int) -> Scenario:
    """
    Get a scenario by name.

    Args:
        name: Scenario name (e.g., "trivial_cooperation", "default")
        num_agents: Number of agents in the scenario

    Returns:
        Scenario object

    Raises:
        ValueError: If scenario name is invalid

    Example:
        >>> scenario = get_scenario_by_name("trivial_cooperation", num_agents=4)
    """
    if name not in SCENARIO_REGISTRY:
        valid_names = ", ".join(sorted(SCENARIO_REGISTRY.keys()))
        raise ValueError(f"Unknown scenario '{name}'. Valid options: {valid_names}")

    return SCENARIO_REGISTRY[name](num_agents)


def list_scenarios() -> list:
    """
    Get list of available scenario names.

    Returns:
        Sorted list of scenario names

    Example:
        >>> scenarios = list_scenarios()
        >>> print(scenarios)
        ['chain_reaction', 'deceptive_calm', 'default', ...]
    """
    return sorted(SCENARIO_REGISTRY.keys())
