#!/usr/bin/env python3
"""
Generate Python code from JSON definitions.

This script reads JSON definitions and generates Python modules.
"""

import json
import sys
from pathlib import Path
from textwrap import dedent


def generate_archetypes(json_path: Path, output_path: Path):
    """Generate archetypes.py from JSON."""
    with open(json_path) as f:
        data = json.load(f)

    archetypes = data['archetypes']

    # Generate Python code
    code = dedent('''\
    """
    Agent archetypes - GENERATED FILE

    This file is automatically generated from definitions/archetypes.json
    DO NOT EDIT MANUALLY - changes will be overwritten

    To modify archetypes, edit definitions/archetypes.json and run:
        python scripts/generate_python.py
    """

    import numpy as np

    ''')

    # Generate individual archetype constants
    for name, spec in archetypes.items():
        constant_name = f"{name.upper()}_PARAMS"
        code += f"# {spec['description']}\n"
        code += f"{constant_name} = np.array([\n"
        for param in spec['params']:
            code += f"    {param},\n"
        code += "], dtype=np.float32)\n\n"

    # Generate ARCHETYPES dictionary
    code += "\n# Registry of all archetypes\n"
    code += "ARCHETYPES = {\n"
    for name in archetypes.keys():
        constant_name = f"{name.upper()}_PARAMS"
        code += f'    "{name}": {constant_name},\n'
    code += "}\n"

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(code)

    print(f"✓ Generated {output_path}")


def generate_scenarios(json_path: Path, output_path: Path):
    """Generate scenarios.py from JSON."""
    with open(json_path) as f:
        data = json.load(f)

    scenarios = data['scenarios']

    # Generate Python code
    code = dedent('''\
    """
    Scenario definitions - GENERATED FILE

    This file is automatically generated from definitions/scenarios.json
    DO NOT EDIT MANUALLY - changes will be overwritten

    To modify scenarios, edit definitions/scenarios.json and run:
        python scripts/generate_python.py
    """

    from dataclasses import dataclass
    import numpy as np


    @dataclass
    class Scenario:
        """Represents the stochastic configuration of a game."""

        # Fire spread and extinguishing parameters
        beta: float  # Fire spread probability per neighbor
        kappa: float  # Extinguish efficiency

        # Reward parameters
        A: float  # Reward per saved house
        L: float  # Penalty per ruined house
        c: float  # Cost per worker per night

        # Initial conditions
        rho_ignite: float  # Initial fraction of houses burning
        N_min: int  # Minimum nights before termination
        p_spark: float  # Probability of spontaneous ignition
        N_spark: int  # Number of nights with sparks active

        # Game setup
        num_agents: int  # Number of agents participating

        def to_feature_vector(self) -> np.ndarray:
            """
            Convert scenario parameters to a feature vector for agent conditioning.
            Returns a numpy array with scenario features.
            """
            return np.array(
                [
                    self.beta,
                    self.kappa,
                    self.A,
                    self.L,
                    self.c,
                    self.rho_ignite,
                    self.N_min,
                    self.p_spark,
                    self.N_spark,
                    self.num_agents,
                ],
                dtype=np.float32,
            )


    ''')

    # Generate factory functions
    for name, spec in scenarios.items():
        function_name = f"{name}_scenario"
        code += f'def {function_name}(num_agents: int) -> Scenario:\n'
        code += f'    """{spec["description"]}"""\n'
        code += f'    return Scenario(\n'
        code += f'        beta={spec["beta"]},\n'
        code += f'        kappa={spec["kappa"]},\n'
        code += f'        A={spec["A"]},\n'
        code += f'        L={spec["L"]},\n'
        code += f'        c={spec["c"]},\n'
        code += f'        rho_ignite={spec["rho_ignite"]},\n'
        code += f'        N_min={spec["N_min"]},\n'
        code += f'        p_spark={spec["p_spark"]},\n'
        code += f'        N_spark={spec["N_spark"]},\n'
        code += f'        num_agents=num_agents,\n'
        code += f'    )\n\n\n'

    # Generate SCENARIO_REGISTRY
    code += "\n# Registry of all scenarios\n"
    code += "SCENARIO_REGISTRY = {\n"
    for name in scenarios.keys():
        function_name = f"{name}_scenario"
        code += f'    "{name}": {function_name},\n'
    code += "}\n\n\n"

    # Generate helper functions
    code += dedent('''
    def get_scenario_by_name(name: str, num_agents: int) -> Scenario:
        """
        Get a scenario by name.

        Args:
            name: Scenario name (e.g., "trivial_cooperation", "default")
            num_agents: Number of agents in the scenario

        Returns:
            Scenario object

        Raises:
            ValueError: If scenario name is invalid

        Example:
            >>> scenario = get_scenario_by_name("trivial_cooperation", num_agents=4)
        """
        if name not in SCENARIO_REGISTRY:
            valid_names = ", ".join(sorted(SCENARIO_REGISTRY.keys()))
            raise ValueError(f"Unknown scenario '{name}'. Valid options: {valid_names}")

        return SCENARIO_REGISTRY[name](num_agents)


    def list_scenarios() -> list:
        """
        Get list of available scenario names.

        Returns:
            Sorted list of scenario names

        Example:
            >>> scenarios = list_scenarios()
            >>> print(scenarios)
            ['chain_reaction', 'deceptive_calm', 'default', ...]
        """
        return sorted(SCENARIO_REGISTRY.keys())
    ''')

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(code)

    print(f"✓ Generated {output_path}")


def main():
    """Generate all Python modules from JSON."""
    root = Path(__file__).parent.parent
    definitions_dir = root / "definitions"

    generate_archetypes(
        definitions_dir / "archetypes.json",
        root / "bucket_brigade" / "agents" / "archetypes_generated.py"
    )

    generate_scenarios(
        definitions_dir / "scenarios.json",
        root / "bucket_brigade" / "envs" / "scenarios_generated.py"
    )

    print("\n✓ Python code generation complete!")


if __name__ == "__main__":
    main()
