#!/usr/bin/env python3
"""
Generate Python code from JSON definitions.

This script reads JSON definitions and generates Python modules.
"""

import json
import sys
from pathlib import Path
from textwrap import dedent


def generate_archetypes(json_path: Path, output_path: Path):
    """Generate archetypes.py from JSON."""
    with open(json_path) as f:
        data = json.load(f)

    archetypes = data['archetypes']

    # Generate Python code
    code = dedent('''\
    """
    Agent archetypes - GENERATED FILE

    This file is automatically generated from definitions/archetypes.json
    DO NOT EDIT MANUALLY - changes will be overwritten

    To modify archetypes, edit definitions/archetypes.json and run:
        python scripts/generate_python.py
    """

    import numpy as np

    ''')

    # Generate individual archetype constants
    for name, spec in archetypes.items():
        constant_name = f"{name.upper()}_PARAMS"
        code += f"# {spec['description']}\n"
        code += f"{constant_name} = np.array([\n"
        for param in spec['params']:
            code += f"    {param},\n"
        code += "], dtype=np.float32)\n\n"

    # Generate ARCHETYPES dictionary
    code += "\n# Registry of all archetypes\n"
    code += "ARCHETYPES = {\n"
    for name in archetypes.keys():
        constant_name = f"{name.upper()}_PARAMS"
        code += f'    "{name}": {constant_name},\n'
    code += "}\n"

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(code)

    print(f"✓ Generated {output_path}")


def generate_scenarios(json_path: Path, output_path: Path):
    """Generate scenarios.py from JSON."""
    with open(json_path) as f:
        data = json.load(f)

    scenarios = data['scenarios']

    # Generate Python code
    code = dedent('''\
    """
    Scenario definitions - GENERATED FILE

    This file is automatically generated from definitions/scenarios.json
    DO NOT EDIT MANUALLY - changes will be overwritten

    To modify scenarios, edit definitions/scenarios.json and run:
        python scripts/generate_python.py

    Parameter names match Rust implementation (bucket-brigade-core/src/scenarios.rs)
    """

    from dataclasses import dataclass
    from typing import List, Union
    import numpy as np


    @dataclass
    class Scenario:
        """Represents the stochastic configuration of a game.

        All parameter names match the Rust implementation for consistency.

        The four ownership reward fields (``reward_own_house_survives``,
        ``reward_other_house_survives``, ``penalty_own_house_burns``,
        ``penalty_other_house_burns``) are per-agent vectors of length
        ``num_agents`` (issue #198). Scalar inputs are auto-promoted to
        a length-``num_agents`` list of that value by ``__post_init__``
        for backward compatibility with existing scenario definitions.
        """

        # Fire dynamics
        prob_fire_spreads_to_neighbor: float  # Probability fire spreads to adjacent house
        prob_solo_agent_extinguishes_fire: float  # Probability one agent extinguishes fire
        prob_house_catches_fire: float  # Probability house catches fire each night

        # Team scoring (collective outcome)
        team_reward_house_survives: float  # Team reward for each house that survives
        team_penalty_house_burns: float  # Team penalty for each house that burns

        # Individual rewards (ownership-based, per-agent vectors of length num_agents)
        # Scalar inputs are auto-promoted in __post_init__ for backward compat.
        reward_own_house_survives: Union[float, List[float]]  # Per-agent reward when own house survives
        reward_other_house_survives: Union[float, List[float]]  # Per-agent reward when other house survives
        penalty_own_house_burns: Union[float, List[float]]  # Per-agent penalty when own house burns
        penalty_other_house_burns: Union[float, List[float]]  # Per-agent penalty when other house burns

        # Costs and structure
        cost_to_work_one_night: float  # Cost incurred when agent chooses to work
        min_nights: int  # Minimum nights before game can end

        # Game setup
        num_agents: int  # Number of agents participating

        def __post_init__(self) -> None:
            """Auto-promote scalar ownership reward fields to per-agent vectors.

            This is the canonical place where scalar -> list promotion happens
            for issue #198. Existing scenarios with scalar JSON values are
            still valid: a scalar ``v`` becomes ``[v] * num_agents``. Lists
            are validated to have exactly ``num_agents`` entries.
            """
            for fname in (
                "reward_own_house_survives",
                "reward_other_house_survives",
                "penalty_own_house_burns",
                "penalty_other_house_burns",
            ):
                value = getattr(self, fname)
                if isinstance(value, (int, float)):
                    setattr(self, fname, [float(value)] * self.num_agents)
                else:
                    # Already a sequence; coerce to list[float] and validate length.
                    promoted = [float(x) for x in value]
                    if len(promoted) != self.num_agents:
                        raise ValueError(
                            f"Scenario.{fname} has length {len(promoted)} "
                            f"but num_agents={self.num_agents}. Per-agent "
                            f"ownership reward vectors must match num_agents."
                        )
                    setattr(self, fname, promoted)

        def to_feature_vector(self) -> np.ndarray:
            """
            Convert scenario parameters to a feature vector for agent conditioning.

            Returns a numpy array with scenario features. The four per-agent
            ownership reward fields are reduced to their mean across agents
            so the feature vector retains its 12-element layout (#198). For
            scenarios with uniform per-agent weights (the legacy scalar-promoted
            case) the mean equals the original scalar value, preserving
            backward compatibility.
            """
            return np.array(
                [
                    self.prob_fire_spreads_to_neighbor,
                    self.prob_solo_agent_extinguishes_fire,
                    self.prob_house_catches_fire,
                    self.team_reward_house_survives,
                    self.team_penalty_house_burns,
                    float(np.mean(self.reward_own_house_survives)),
                    float(np.mean(self.reward_other_house_survives)),
                    float(np.mean(self.penalty_own_house_burns)),
                    float(np.mean(self.penalty_other_house_burns)),
                    self.cost_to_work_one_night,
                    self.min_nights,
                    self.num_agents,
                ],
                dtype=np.float32,
            )


    ''')

    # Generate factory functions
    # Ownership reward fields are emitted as the literal value from JSON --
    # scalar or list. The Scenario dataclass __post_init__ auto-promotes
    # scalars to length-num_agents vectors (issue #198).
    def _emit_value(v):
        # Emit Python literal for either a scalar or a list of scalars.
        if isinstance(v, list):
            return "[" + ", ".join(repr(float(x)) for x in v) + "]"
        return repr(v)

    for name, spec in scenarios.items():
        function_name = f"{name}_scenario"
        code += f'def {function_name}(num_agents: int) -> Scenario:\n'
        code += f'    """{spec["description"]}"""\n'
        code += f'    return Scenario(\n'
        code += f'        prob_fire_spreads_to_neighbor={spec["prob_fire_spreads_to_neighbor"]},\n'
        code += f'        prob_solo_agent_extinguishes_fire={spec["prob_solo_agent_extinguishes_fire"]},\n'
        code += f'        prob_house_catches_fire={spec["prob_house_catches_fire"]},\n'
        code += f'        team_reward_house_survives={spec["team_reward_house_survives"]},\n'
        code += f'        team_penalty_house_burns={spec["team_penalty_house_burns"]},\n'
        code += f'        reward_own_house_survives={_emit_value(spec["reward_own_house_survives"])},\n'
        code += f'        reward_other_house_survives={_emit_value(spec["reward_other_house_survives"])},\n'
        code += f'        penalty_own_house_burns={_emit_value(spec["penalty_own_house_burns"])},\n'
        code += f'        penalty_other_house_burns={_emit_value(spec["penalty_other_house_burns"])},\n'
        code += f'        cost_to_work_one_night={spec["cost_to_work_one_night"]},\n'
        code += f'        min_nights={spec["min_nights"]},\n'
        code += f'        num_agents=num_agents,\n'
        code += f'    )\n\n\n'

    # Generate SCENARIO_REGISTRY
    code += "\n# Registry of all scenarios\n"
    code += "SCENARIO_REGISTRY = {\n"
    for name in scenarios.keys():
        function_name = f"{name}_scenario"
        code += f'    "{name}": {function_name},\n'
    code += "}\n\n\n"

    # Generate helper functions
    code += dedent('''
    def get_scenario_by_name(name: str, num_agents: int) -> Scenario:
        """
        Get a scenario by name.

        Args:
            name: Scenario name (e.g., "trivial_cooperation", "default")
            num_agents: Number of agents in the scenario

        Returns:
            Scenario object

        Raises:
            ValueError: If scenario name is invalid

        Example:
            >>> scenario = get_scenario_by_name("trivial_cooperation", num_agents=4)
        """
        if name not in SCENARIO_REGISTRY:
            valid_names = ", ".join(sorted(SCENARIO_REGISTRY.keys()))
            raise ValueError(f"Unknown scenario '{name}'. Valid options: {valid_names}")

        return SCENARIO_REGISTRY[name](num_agents)


    def list_scenarios() -> list:
        """
        Get list of available scenario names.

        Returns:
            Sorted list of scenario names

        Example:
            >>> scenarios = list_scenarios()
            >>> print(scenarios)
            ['chain_reaction', 'deceptive_calm', 'default', ...]
        """
        return sorted(SCENARIO_REGISTRY.keys())
    ''')

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(code)

    print(f"✓ Generated {output_path}")


def main():
    """Generate all Python modules from JSON."""
    root = Path(__file__).parent.parent
    definitions_dir = root / "definitions"

    generate_archetypes(
        definitions_dir / "archetypes.json",
        root / "bucket_brigade" / "agents" / "archetypes_generated.py"
    )

    generate_scenarios(
        definitions_dir / "scenarios.json",
        root / "bucket_brigade" / "envs" / "scenarios_generated.py"
    )

    print("\n✓ Python code generation complete!")


if __name__ == "__main__":
    main()
